# Generated by Django 6.0.2 on 2026-03-02 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_profile_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(256)]),
        ),
    ]
